### ISSUE TITLE
Known sequences statistics?

### ISSUE THREAD

**Issue by Mark79864** [derwin12/mywebscrape#103]
Could there be a 'statistics' page which lists information from all the sequences found?
Statistics such as:
- Box & whisker plot of paid sequence prices with average price.
- Pie chart showing the percentage of free VS UXSG VS paid sequences.
- Dot plot of sequences found during the year - chart describing most popular times of the year when sequences are made (paid & free).

Just a few ideas for some statistics for the useful information you have avaliable.
Thankyou for this site.

**Comment by derwin12** [comment]
I have captured this via google analytics .. not available for public consumption but can provide some insights if asked.
