### ISSUE TITLE
New vendor

### ISSUE THREAD

**Issue by derwin12** [derwin12/mywebscrape#115]
Not much there...
https://pixelsmaven.com/

**Comment by derwin12** [comment]
Another small one
https://rgbdisplays.com/products/straight-no-chaser-12-days-of-christmas

**Comment by RGBDisplays** [comment]
Thanks for creating this page, I'll update here when I create more .
https://rgbdisplays.com/products/perry-como-christmas-dream (Free)
https://rgbdisplays.com/products/straight-no-chaser-12-days-of-christmas
https://rgbdisplays.com/products/human-nature-christmas-baby-please-come-home
https://rgbdisplays.com/products/dean-martin-let-it-snow
https://rgbdisplays.com/products/michael-buble-holly-jolly-christmas

**Comment by MrPaulAR** [comment]
Looks like the page to scrape is
https://rgbdisplays.com/collections/xlight-sequences
