### ISSUE TITLE
Missing Sequences

### ISSUE THREAD

**Issue by RGBDisplays** [derwin12/mywebscrape#134]
Hi all, You are doing a great job here. I recently added halloween sequences to my site and may have changes the way you scrap for the sequences, all sequences are now https://rgbdisplays.com/collections/xlights-sequences

Noticed a few of the newer ones are missing

Thanks Again

**Comment by derwin12** [comment]
That is the link I scrape.. so let me see if there is an error.
https://rgbdisplays.com/collections/xlight-sequences
If you have it handy .. what sequence is not showing up?

**Comment by MrPaulAR** [comment]
I see the following ones missing

- [Wizzard - I Wish It Could Be Christmas Everyday](https://rgbdisplays.com/products/wizzard-i-wish-it-could-be-christmas-everyday)
- [AC/DC - Highway To Hell](https://rgbdisplays.com/products/ac-dc-high-way-to-hell)

I think the Greensleeves version without Christmas or Halloween should be dropped from the database as it's now broken out individually on his site.

**Comment by RGBDisplays** [comment]
Yes that’s the ones which are missing. 👍

**Comment by derwin12** [comment]
The website was doing a redirect when I pulled and resulted in it being skipped.
