### ISSUE TITLE
New sequence missed from 6/13/24

### ISSUE THREAD

**Issue by ucfknight98** [derwin12/mywebscrape#153]
https://www.solsequencing.com/Its-the-Most-Wonderful-Time-of-the-Year-Andy-Williams-2024-Layout-p671566469

**Comment by derwin12** [comment]
I think I only scan the main page .. it is not there?
https://www.solsequencing.com/xLights-Sequences-c129729145

**Comment by ucfknight98** [comment]
100% my fault, ugh, it wasn't on the main page. Sorry to bug you but thanks for all you do!!!
