### ISSUE TITLE
New Vendor: Spark To Light Sequences

### ISSUE THREAD

**Issue by ad-lightshow** [derwin12/mywebscrape#154]
We are a new xLights sequence vendor, requesting to be added to xlights.info.

The website is sparktolights.com. If you are getting sequence data via scraping, I think you will want to use: https://sparktolights.com/collection/all

Thank you in advance for adding us to the list!

**Comment by derwin12** [comment]
It would be VERY helpful if the pricing was on the main page(s).

**Comment by ad-lightshow** [comment]
Thank you for responding. My apologies, I am a little confused by what you need for that -- our website is set up similar to other sites that are currently linked to your site, so I had assumed it would also work. Do you have an example of one that is in line with what you're describing? Is it possible to still link to your site as it is? Again, my apologies if there are technical reasons that I am unfamiliar with.

**Comment by derwin12** [comment]
I will work on adding it ..
the difference is everyone else puts a price on their main page. Without
it, to scrape I need to hit each and every one of your pages..every time..
eg.
[image: image.png]

Yours .. no price unless I click thru..
[image: image.png]

**Comment by derwin12** [comment]
Done.
