### ISSUE TITLE
Change of Scrape to match prices in $ RGBDisplays.com

### ISSUE THREAD

**Issue by RGBDisplays** [derwin12/mywebscrape#156]
Hi all, is it possible to change the scape to use 
https://rgbdisplays.com/en-us/collections/xlights-sequences
This will hopefully allow the prices to come through as the correct USD rather than the current GBP turned into USD.
Hope this makes sense.

**Comment by derwin12** [comment]
I can try but I think it is more of me being in Canada .. so I only see the Canadian prices if your site automagically flips it.

**Comment by derwin12** [comment]
That is what I am using. The ecommerce site is just dishing me up Canadian $$. I will try again to see if I can lie to it that I am US$.

`101 | https://rgbdisplays.com/collections/xlight-sequences | RGB Displays`

**Comment by derwin12** [comment]
Oh wait .. i just noticed your subtle difference in the url.. let me change that.

**Comment by RGBDisplays** [comment]
Fingers crossed 🤞

**Comment by derwin12** [comment]
Done .. had to reload the entries as well.
