### ISSUE TITLE
xLights Sequences: Remove Vendor Sequences

### ISSUE THREAD

**Issue by MrPaulAR** [derwin12/mywebscrape#41]
Looks like all of the Vendor sequences are in various forums that include the word Vendor.  This can be parsed out on initial scrape and ignored.

Element is class="structItem-parts".  In that there are some list items and currently the last one has the text attribute containing the subforum name.  Could do something to parse these out and skip them.

Stuff in the DB currently would need to be dropped though and re-scraped.

**Comment by derwin12** [comment]
I did add the code to pull in the $$ so atleast they are not being flagged as free. Originally the site was hard coded to price='Free' since they were originally all free.

**Comment by MrPaulAR** [comment]
I was thinking about a way to reduce the chance of a vendor's sequences showing up multiple times in search results.
