### ISSUE TITLE
Add Store Homepage URL

### ISSUE THREAD

**Issue by MrPaulAR** [derwin12/mywebscrape#76]
Should we add a new field to the database for the store homepage?  This can be used instead of picking the first url from Vendor.urls which is what we are doing today.

**Comment by derwin12** [comment]
Either that or take the basename of the first url -- does basename hold
true 100% of the time?

**Comment by MrPaulAR** [comment]
Looking through the BaseUrls table this (the url root) seems like the
simplest solution.
