### ISSUE TITLE
Automated scrapers -- need to exclude the gd google drive ones...

### ISSUE THREAD

**Issue by derwin12** [derwin12/mywebscrape#92]
https://github.com/derwin12/mywebscrape/blob/ab9be2ac57943b1c770b883421949465fc52ff9a/app/run_scrapers.py#L8

They never change .. just leave the gdNew.py
skip gdOther and gdChristmas

**Comment by derwin12** [comment]
and skip uxsg

**Comment by MrPaulAR** [comment]
Those are now skipped.

**Comment by derwin12** [comment]
I am good with this .. if you want to merge..

**Comment by MrPaulAR** [comment]
Merged along with #91
